#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0;
		policy drop;

		ct state established,related accept

		udp dport 53 accept
		tcp dport 53 accept
		tcp dport 80 accept
		tcp dport 443 accept

		udp dport 1194 accept
	}
	chain forward {
		type filter hook forward priority 0;
		policy drop;

		ct state established,related accept

		iif "ens33" oif "ens32" accept
		iif "ens34" oif "ens32" accept

		iif "tun0" oif "ens33" accept
		iif "tun0" oif "ens34" accept

		ip daddr 10.10.10.10 udp dport 53 accept
		ip daddr 10.10.10.10 tcp dport 53 accept
		ip daddr 192.168.26.123 tcp dport 80 accept
		ip daddr 192.168.26.123 tcp dport 443 accept

		ip saddr 192.168.26.10 ip daddr 10.10.10.10 tcp dport 389 accept
	}
	chain output {
		type filter hook output priority filter;
	}
}

table ip nat {
	chain prerouting {
		type nat hook prerouting priority -100;

		iif "ens32" udp dport 53 dnat to 10.10.10.10:53
		iif "ens32" tcp dport 53 dnat to 10.10.10.10:53
		iif "ens32" tcp dport 80 dnat to 192.168.26.123:80
		iif "ens32" tcp dport 443 dnat to 192.168.26.123:443
	}

	chain postrouting {
		type nat hook postrouting priority 100;

		oif "ens32" masquerade
	}
}
