---

- name: Playbook 2 Windows
  hosts: Windows

  tasks:
    - name: Stop RDP Service
      win_service:
        name: TermService
        state: stopped

    - name: Disable RDP Service
      win_service:
        name: TermService
        start_mode: disabled