#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority filter;
		policy drop;

		ct state established,related accept

		iif "lo" accept
		ip protocol icmp accept
		tcp dport 22 accept
	}
	chain forward {
		type filter hook forward priority filter;
		policy drop;

		ct state established,related accept

		iif "ens32" oif "ens33" accept

		iif "ens32" oif "ens33" udp dport 1194 accept
	}
	chain output {
		type filter hook output priority filter;
	}
}

table ip nat {
	chain postrouting {
		type nat hook postrouting priority 100;

		oif "ens33" masquerade
	}
}
