#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority filter;
		policy drop;

		ct state established,related accept

		iif "lo" accept
		ip protocol icmp accept
		tcp dport 22 accept

		udp dport 53 accept
		tcp dport 53 accept
		tcp dport 80 accept
		tcp dport 443 accept

		udp dport 1194 accept
	}
	chain forward {
		type filter hook forward priority filter;
		policy drop;

		ct state established,related accept

		iif "tun0" oif "ens32" accept

		iif "ens32" oif "ens33" accept

		ip daddr 10.10.10.10 udp dport 53 accept
		ip daddr 10.10.10.10 tcp dport 53 accept

	}
	chain output {
		type filter hook output priority filter;
	}
}

table ip nat {
	chain prerouting {
		type nat hook prerouting priority -100;

		iif "ens33" ip daddr 32.12.10.110 udp dport 53 dnat to 10.10.10.10:53
		iif "ens33" ip daddr 32.12.10.110 tcp dport 53 dnat to 10.10.10.10:53
	}

	chain postrouting {
		type nat hook postrouting priority 100;

		oif "ens33" masquerade
	}
}
