---

- name: Playbook 1 Linux
  hosts: Linux
  become: yes

  tasks:
    - name: Set Linux Hostname
      hostname:
        name: "{{ hostname }}"
      notify: restart server

  handlers:
    - name: restart server
      reboot: